defaults: &defaults
  working_directory: ~/welcome-ui
  docker:
    - image: circleci/node:10.15.1-browsers

defaults_deploy: &defaults_deploy
  working_directory: ~/welcome-ui
  machine: true

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/welcome-ui

  yarn_install:
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn install
      - store_artifacts:
          path: yarn.lock
      - persist_to_workspace:
          root: ~/welcome-ui
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/welcome-ui
      - restore_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/welcome-ui
      - restore_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test

  docs_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/welcome-ui
      - restore_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn docz:build
      - persist_to_workspace:
          root: ~/welcome-ui
          paths:
            - docs/*

  docs_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/welcome-ui
      - run: yarn install --production=false
      - run:
          name: list files
          command: ls docs/**/*
      - restore_cache:
          key: v2-welcome-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn docz:deploy --domain welcome-ui.{{ CIRCLE_BRANCH }}.surge.sh

workflows:
  version: 2
  btd:
    jobs:
      - checkout
      - yarn_install:
          requires:
            - checkout
      - lint:
          requires:
            - yarn_install
      - test:
          requires:
            - yarn_install
      - docs_build:
          requires:
            - lint
            - test
      - docs_deploy:
          requires:
            - docs_build
        
